# Generated by Django 3.2.15 on 2022-11-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_semester_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='learning.entity'),
        ),
    ]
