# Generated by Django 3.2.15 on 2022-11-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_department_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='learning.department'),
        ),
    ]
