# Generated by Django 3.2.15 on 2022-11-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_semester_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
