# Generated by Django 3.2.15 on 2022-11-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_file1',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_file2',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/'),
        ),
    ]
